const GRAPHQL_SCHEMA_SCRIPT_INDENT = '  ';

const QUERY_ROOT_TYPE = 'Query';
const MUTATION_ROOT_TYPE = 'Mutation';
const SUBSCRIPTION_ROOT_TYPE = 'Subscription';

const MISSED_ARG_TYPE_COMMENT = 'MISSING ARGUMENT TYPE';

module.exports = {
	GRAPHQL_SCHEMA_SCRIPT_INDENT,
	QUERY_ROOT_TYPE,
	MUTATION_ROOT_TYPE,
	SUBSCRIPTION_ROOT_TYPE,
	MISSED_ARG_TYPE_COMMENT,
};
